name: Playwright Tests # Name of the pipelines
on: #Specifies when this pipeline runes
  push:
    brances: [main] #  Run when we push on branch 'main'
jobs: # This is the list of jobs it runs when we push to main branch
  playwrighttests:
    runs-on: ubuntu-latest #runs on specific Operating system
    container: # run on a specific container
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
      env:
        ADMIN_USER: ${{ secrets.ADMIN_USER }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps: # This is the steps to perform by the action
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Start the shopping store application"
          chmod +x ./shopping-store-linux-amd64
          ./shopping-store-linux-amd64 &
          echo "Install dependencies from lockfile"
          npm ci
          echo "Run Playwright tests"
          npm run test:ci
